# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_macosx
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

TARGETDIR = ../../build/bin
TARGET = $(TARGETDIR)/fastProgram
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LDDEPS +=
LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug_macosx)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
OBJDIR = ../../build/obj/fastProgram-macosx-debug
DEFINES += -DME_VERSION=\"9.2.0\" -DME_APPWEB_PRODUCT=1 -DME_APP_PREFIX=\"/usr/local/lib/appweb\" -DME_COM_CGI=1 -DME_COM_FAST=1 -DME_COM_PROXY=1 -DME_HTTP_BASIC=1 -DME_HTTP_CACHE=1 -DME_HTTP_CMD=1 -DME_HTTP_DEFENSE=1 -DME_HTTP_DIGEST=1 -DME_HTTP_DIR=1 -DME_HTTP_HTTP2=1 -DME_HTTP_PAM=1 -DME_HTTP_SENDFILE=1 -DME_HTTP_UPLOAD=1 -DME_HTTP_WEB_SOCKETS=1 -DME_COM_PCRE2=0 -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_SSL=1 -DME_COM_MBEDTLS_PATH=\"/usr\" -DME_COM_OPENSSL_PATH=\"/opt/homebrew\" -DME_DEBUG=1
INCLUDES += -I../../src -I../../src/osdep -I../../src/mpr -I../../src/http -I/opt/homebrew/include
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O0 -g -Wall -Wextra -std=gnu11 -Wno-sign-conversion -Wno-unused-parameter -Wno-unused-result -Wshorten-64-to-32 -Wall -Wno-unknown-warning-option -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wno-sign-compare -Wno-cast-function-type-mismatch -Wno-shorten-64-to-32
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O0 -g -Wall -Wextra -Wno-sign-conversion -Wno-unused-parameter -Wno-unused-result -Wshorten-64-to-32 -Wall -Wno-unknown-warning-option -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wno-sign-compare -Wno-cast-function-type-mismatch -Wno-shorten-64-to-32
LIBS += -ldl -lpthread -lm -lpam -lfcgi
ALL_LDFLAGS += $(LDFLAGS) -L/opt/homebrew/lib -g -Wl,-no_warn_duplicate_libraries -Wl,-rpath,@executable_path/ -Wl,-rpath,@loader_path/

else ifeq ($(config),debug_linux)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
OBJDIR = ../../build/obj/fastProgram-linux-debug
DEFINES += -DME_VERSION=\"9.2.0\" -DME_APPWEB_PRODUCT=1 -DME_APP_PREFIX=\"/usr/local/lib/appweb\" -DME_COM_CGI=1 -DME_COM_FAST=1 -DME_COM_PROXY=1 -DME_HTTP_BASIC=1 -DME_HTTP_CACHE=1 -DME_HTTP_CMD=1 -DME_HTTP_DEFENSE=1 -DME_HTTP_DIGEST=1 -DME_HTTP_DIR=1 -DME_HTTP_HTTP2=1 -DME_HTTP_PAM=1 -DME_HTTP_SENDFILE=1 -DME_HTTP_UPLOAD=1 -DME_HTTP_WEB_SOCKETS=1 -DME_COM_PCRE2=0 -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_SSL=1 -DME_COM_MBEDTLS_PATH=\"/usr\" -DME_COM_OPENSSL_PATH=\"/usr\" -DME_DEBUG=1
INCLUDES += -I../../src -I../../src/osdep -I../../src/mpr -I../../src/http
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O0 -g -Wall -Wextra -std=gnu11 -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O0 -g -Wall -Wextra -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
LIBS += -lrt -ldl -lpthread -lm -lfcgi
ALL_LDFLAGS += $(LDFLAGS) -g -Wl,-z,relro,-z,now -Wl,--as-needed -Wl,--no-copy-dt-needed-entries -Wl,-z,noexecheap -Wl,--no-warn-execstack

else ifeq ($(config),debug_freebsd)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
OBJDIR = ../../build/obj/fastProgram-freebsd-debug
DEFINES += -DME_VERSION=\"9.2.0\" -DME_APPWEB_PRODUCT=1 -DME_APP_PREFIX=\"/usr/local/lib/appweb\" -DME_COM_CGI=1 -DME_COM_FAST=1 -DME_COM_PROXY=1 -DME_HTTP_BASIC=1 -DME_HTTP_CACHE=1 -DME_HTTP_CMD=1 -DME_HTTP_DEFENSE=1 -DME_HTTP_DIGEST=1 -DME_HTTP_DIR=1 -DME_HTTP_HTTP2=1 -DME_HTTP_PAM=1 -DME_HTTP_SENDFILE=1 -DME_HTTP_UPLOAD=1 -DME_HTTP_WEB_SOCKETS=1 -DME_COM_PCRE2=0 -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_SSL=1 -DME_COM_MBEDTLS_PATH=\"/usr\" -DME_COM_OPENSSL_PATH=\"/usr\" -DME_DEBUG=1
INCLUDES += -I../../src -I../../src/osdep -I../../src/mpr -I../../src/http
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O0 -g -Wall -Wextra -std=gnu11 -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O0 -g -Wall -Wextra -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
LIBS += -ldl -lpthread -lm -lfcgi
ALL_LDFLAGS += $(LDFLAGS) -g

else ifeq ($(config),release_macosx)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
OBJDIR = ../../build/obj/fastProgram-macosx-release
DEFINES += -DME_VERSION=\"9.2.0\" -DME_APPWEB_PRODUCT=1 -DME_APP_PREFIX=\"/usr/local/lib/appweb\" -DME_COM_CGI=1 -DME_COM_FAST=1 -DME_COM_PROXY=1 -DME_HTTP_BASIC=1 -DME_HTTP_CACHE=1 -DME_HTTP_CMD=1 -DME_HTTP_DEFENSE=1 -DME_HTTP_DIGEST=1 -DME_HTTP_DIR=1 -DME_HTTP_HTTP2=1 -DME_HTTP_PAM=1 -DME_HTTP_SENDFILE=1 -DME_HTTP_UPLOAD=1 -DME_HTTP_WEB_SOCKETS=1 -DME_COM_PCRE2=0 -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_SSL=1 -DME_COM_MBEDTLS_PATH=\"/usr\" -DME_COM_OPENSSL_PATH=\"/opt/homebrew\"
INCLUDES += -I../../src -I../../src/osdep -I../../src/mpr -I../../src/http -I/opt/homebrew/include
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -Wall -Wextra -std=gnu11 -Wno-sign-conversion -Wno-unused-parameter -Wno-unused-result -Wshorten-64-to-32 -Wall -Wno-unknown-warning-option -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wno-sign-compare -Wno-cast-function-type-mismatch -Wno-shorten-64-to-32
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -Wall -Wextra -Wno-sign-conversion -Wno-unused-parameter -Wno-unused-result -Wshorten-64-to-32 -Wall -Wno-unknown-warning-option -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wno-sign-compare -Wno-cast-function-type-mismatch -Wno-shorten-64-to-32
LIBS += -ldl -lpthread -lm -lpam -lfcgi
ALL_LDFLAGS += $(LDFLAGS) -L/opt/homebrew/lib -Wl,-no_warn_duplicate_libraries -Wl,-rpath,@executable_path/ -Wl,-rpath,@loader_path/

else ifeq ($(config),release_linux)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
OBJDIR = ../../build/obj/fastProgram-linux-release
DEFINES += -DME_VERSION=\"9.2.0\" -DME_APPWEB_PRODUCT=1 -DME_APP_PREFIX=\"/usr/local/lib/appweb\" -DME_COM_CGI=1 -DME_COM_FAST=1 -DME_COM_PROXY=1 -DME_HTTP_BASIC=1 -DME_HTTP_CACHE=1 -DME_HTTP_CMD=1 -DME_HTTP_DEFENSE=1 -DME_HTTP_DIGEST=1 -DME_HTTP_DIR=1 -DME_HTTP_HTTP2=1 -DME_HTTP_PAM=1 -DME_HTTP_SENDFILE=1 -DME_HTTP_UPLOAD=1 -DME_HTTP_WEB_SOCKETS=1 -DME_COM_PCRE2=0 -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_SSL=1 -DME_COM_MBEDTLS_PATH=\"/usr\" -DME_COM_OPENSSL_PATH=\"/usr\"
INCLUDES += -I../../src -I../../src/osdep -I../../src/mpr -I../../src/http
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -Wall -Wextra -std=gnu11 -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -Wall -Wextra -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
LIBS += -lrt -ldl -lpthread -lm -lfcgi
ALL_LDFLAGS += $(LDFLAGS) -s -Wl,-z,relro,-z,now -Wl,--as-needed -Wl,--no-copy-dt-needed-entries -Wl,-z,noexecheap -Wl,--no-warn-execstack

else ifeq ($(config),release_freebsd)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
OBJDIR = ../../build/obj/fastProgram-freebsd-release
DEFINES += -DME_VERSION=\"9.2.0\" -DME_APPWEB_PRODUCT=1 -DME_APP_PREFIX=\"/usr/local/lib/appweb\" -DME_COM_CGI=1 -DME_COM_FAST=1 -DME_COM_PROXY=1 -DME_HTTP_BASIC=1 -DME_HTTP_CACHE=1 -DME_HTTP_CMD=1 -DME_HTTP_DEFENSE=1 -DME_HTTP_DIGEST=1 -DME_HTTP_DIR=1 -DME_HTTP_HTTP2=1 -DME_HTTP_PAM=1 -DME_HTTP_SENDFILE=1 -DME_HTTP_UPLOAD=1 -DME_HTTP_WEB_SOCKETS=1 -DME_COM_PCRE2=0 -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_SSL=1 -DME_COM_MBEDTLS_PATH=\"/usr\" -DME_COM_OPENSSL_PATH=\"/usr\"
INCLUDES += -I../../src -I../../src/osdep -I../../src/mpr -I../../src/http
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -Wall -Wextra -std=gnu11 -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -Wall -Wextra -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
LIBS += -ldl -lpthread -lm -lfcgi
ALL_LDFLAGS += $(LDFLAGS) -s

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/fastProgram.o
OBJECTS += $(OBJDIR)/fastProgram.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo "      [Link] fastProgram"
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo "     [Clean] fastProgram"
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) $(foreach f,$(subst /,\\,$(GENERATED)),if exist $(f) del /s /q $(f) >nul &)
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/fastProgram.o: ../../src/utils/fastProgram.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif
