/*
    response.tst.ts - Response flow control across every handler

    A client that reads slowly must still receive every byte, in order. The suite tested that for two
    gateways -- cgi/pausing.tst.ts and fast/pausing.tst.ts -- and for nothing else. fileHandler,
    actionHandler and proxyHandler had no slow-reader test at all, and basic/stream.tst.ts, which
    looks like one, reads a 100KB document in slices with no delay: it never fills a queue and would
    pass against a server with backpressure removed.

    Each handler reaches the network by a different route through the pipeline -- the file handler can
    hand a descriptor to sendfile, the gateways copy through their own connectors, the proxy relays
    another server's output -- so "flow control works" verified for one of them says nothing about the
    others.

    HOW the client is slow is the whole design; see slow.ts. Briefly: it pauses the socket rather than
    sleeping between reads, so the receive window actually closes.

    WHAT is asserted is the second design decision. Each handler is read twice, once at full speed and
    once slowly, and the two must agree byte for byte at the head, the tail and the total. Comparing
    against the fast read rather than against a hardcoded length is not laziness: the gateway programs
    wrap their output in HTML of their own, so a literal would encode cgiProgram's framing into a test
    about flow control and would have to be rederived whenever that program changed. The property
    under test is that slowing the reader changes nothing, and that is exactly what this compares.

    Absolute sizes are still asserted where they are known independently of the server -- the file on
    disk, and the byte count the action fixture was asked for -- so a run where both reads are equally
    wrong cannot pass.
 */

import {teq, tinfo, tskip, ttrue} from '@embedthis/testme'

import {SlowReply, slowRead} from './slow'
import {HAS_FAST, HAS_PROXY, NO_FAST, NO_PROXY} from '../utils/gateways'

//  Big enough to fill the write queue many times over. LimitPacket is 8K in test/appweb.conf.
const MB = 1024 * 1024

//  web/1M.txt, generated by prep.sh: 20972 lines of 49 digits plus "END OF DOCUMENT"
const FILE_SIZE = 20972 * 50 + 16
const LINE = '0123456789012345678901234567890123456789012345678'

//  What the gateway programs are asked to emit. Their own framing sits around it, which is why the
//  totals below are compared against a fast read rather than against a computed literal.
const UNIT = 32768

interface Pair {
    fast: SlowReply
    slow: SlowReply
}

/*
    Read once at speed and once slowly, and require them to agree.

    The pause count is asserted too. Zero or one pause means the whole response arrived before the
    client could slow down, so the case proved nothing -- a silent no-op is the failure mode a
    flow-control test is most likely to have.
 */
async function compare(name: string, path: string, headers?: string[]): Promise<Pair> {
    const options = headers ? {headers} : {}
    const fast = await slowRead(path, {...options, maxPauses: 0})
    const slow = await slowRead(path, {...options, pauseMs: 15, maxPauses: 40})

    tinfo('  ' + name.padEnd(14) + ' ' + slow.bytes + ' bytes, ' + slow.pauses + ' paused reads' +
          (fast.bytes == slow.bytes ? '' : '  (FAST READ SAW ' + fast.bytes + ')'))

    teq(fast.status, 200)
    teq(slow.status, 200)
    if (slow.bytes != fast.bytes) {
        console.log(name + ': slow reader received ' + slow.bytes + ' bytes, fast reader ' + fast.bytes)
    }
    teq(slow.bytes, fast.bytes)
    teq(slow.head, fast.head)
    teq(slow.tail, fast.tail)

    if (slow.pauses < 2) {
        console.log(name + ': the response arrived in ' + slow.pauses + ' chunk(s); the reader was never ' +
            'actually slow, so this case verified nothing')
    }
    ttrue(slow.pauses >= 2)
    return {fast, slow}
}

//  fileHandler. Size known from the file on disk, so this arm does not rest on the comparison alone.
let file = await compare('fileHandler', '/1M.txt')
teq(file.slow.bytes, FILE_SIZE)
ttrue(file.slow.head.startsWith(LINE))
ttrue(file.slow.tail.endsWith('END OF DOCUMENT\n'))

/*
    actionHandler. /action/stream writes with HTTP_BLOCK, so the handler itself blocks when the queue
    fills -- the producer side of flow control, which no other case here exercises: a file is served
    from a descriptor and a gateway's output is paced by the gateway.

    Its size is exactly what was asked for, so it is asserted absolutely.
 */
let action = await compare('actionHandler', '/action/stream?size=' + MB)
teq(action.slow.bytes, MB)
//  The fixture writes 50 digits then a newline, so structure is checked and not only the total
ttrue(action.slow.head.startsWith('01234567890123456789012345678901234567890123456789\n'))

//  cgiHandler
await compare('cgiHandler', '/cgi-bin/cgiProgram', ['SWITCHES: -b%20' + UNIT])

//  fastHandler
if (!HAS_FAST) {
    tskip('fastHandler skipped: ' + NO_FAST)
} else {
    await compare('fastHandler', '/fast-bin/fastProgram?SWITCHES=-b%20' + UNIT)
}

/*
    proxyHandler. The front server is relaying a response it is receiving from the backend while its
    own client refuses to read, so backpressure has to propagate across two servers: the front must
    stop reading from the backend, and the backend must stop writing. A proxy that buffered the whole
    response instead would still pass the byte count and grow without bound -- which is what the soak
    group is for.
 */
if (!HAS_PROXY) {
    tskip('proxyHandler skipped: ' + NO_PROXY)
} else {
    let proxy = await compare('proxyHandler', '/proxy/1M.txt')
    teq(proxy.slow.bytes, FILE_SIZE)
    ttrue(proxy.slow.tail.endsWith('END OF DOCUMENT\n'))
}

/*
    PHP is reachable through both gateways now that Action selects an interpreter, but a slow-reader
    case over a PHP document is not added here: the FastCGI arm above already covers the transport it
    would use, and the response size would be phpinfo's, which varies with the installed build.
 */
